### ISSUE TITLE
Pale Moon support

### ISSUE THREAD

**Issue by mattatobin** [hadalin/firefox-hidefedora#4]
Greetings,

I am the Add-on Site Administrator and Add-ons Team Leader for the Pale Moon project. A divergent and independently developed Mozilla-based browser originally forked from Firefox. Your add-on has been reported as being incompatible with Pale Moon and upon looking into why this is it seems that this extension is technologically compatible with us but is blocked from installing due to install.rdf restrictions.

While we have allowed legacy Firefox add-ons targeted at the Firefox 24 level to install generally without modification this assumes said add-on has a minimum version requirement of 24 or below. However, your add-on has a minver of 26 so it fails to install.

If you would like to directly support the Pale Moon browser you can add a Pale Moon specific application block to your install.rdf as outlined here: http://forum.palemoon.org/viewtopic.php?f=1&t=5440

Thank you for your time and consideration.

-Matt A. Tobin

**Comment by hadalin** [comment]
Lowered minimum version requirement to 24 :)

I don't have install.rdf file. I can make a Pale Moon branch, put whatever is needed there and release it. Just tell me what to put inside install.rdf file and anything else that's needed.

**Comment by mattatobin** [comment]
Umm.. All add-ons need to get an install.rdf. Now I understand if AMO is providing some acceleration tools to generate this on the fly but if you want to support multiple browsers you should be providing AMO with a packaged xpi file.

Can you enlighten me on how you are publishing this add-on with AMO?

**Comment by mattatobin** [comment]
How are you packaging and publishing this add-on?

**Comment by hadalin** [comment]
Using Add-on SDK. Command line tool does everything for you, initializing the project, packaging (making xpi), etc.

**Comment by hadalin** [comment]
Will crack open the xpi and change what needs to be changed. Tomorrow I'm quite busy though.

**Comment by Fogest** [comment]
I'm confused, why isn't a pull request just submitted if this is a specific
request for a 3rd party browser?

Justin V

**Comment by mattatobin** [comment]
@Fogest Because there is NOTHING to do a pull request on. Not without significantly changing how the extension is packaged. Right now it uses the SDK command line tools which when packaging process package.json but it doesn't HAVE any thing to determin targeted applications. It just assumes Firefox and writes it out wholesale. There is nothing in package.json to add.

If I had more time I could likely devise a solution up for this add-on but I don't at this time. Modifying the install.rdf with a quick cut and paste of the Pale Moon target application block is the simplest method right now to provide multiple application support and to support Pale Moon users.

**Comment by Fogest** [comment]
Ah okay, thanks for the application.

Justin V

**Comment by hadalin** [comment]
@mattatobin Changed install.rdf, tested it on Pale Moon and it seems to work nicely https://github.com/hadalin/firefox-hidefedora/tree/palemoon/dist
